# Generated by Django 6.0.7 on 2026-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifition_mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verifition', models.CharField(max_length=4)),
                ('creat_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
