# Generated by Django 6.0.7 on 2026-08-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_verifition_mail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verifition_mail',
            new_name='Verifition',
        ),
    ]
