# Generated by Django 6.0.7 on 2026-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_verifition_mail_verifition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifition',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
