# Generated by Django 6.0.7 on 2026-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(max_length=250, null=True, upload_to='', verbose_name='视频'),
        ),
    ]
