# Generated by Django 6.0.7 on 2026-08-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_options_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': '帖子媒体', 'verbose_name_plural': '帖子媒体'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updata_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_at',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='post/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('video', '视频'), ('file', '文件')], default='file', max_length=20, verbose_name='媒体类型'),
        ),
    ]
