# Generated by Django 6.0.7 on 2026-07-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], help_text='性别', max_length=6, null=True)),
                ('birthday', models.DateField(blank=True, help_text='出生日期', null=True)),
                ('clazz', models.CharField(blank=True, help_text='班级', max_length=50, null=True)),
                ('address', models.TextField(blank=True, help_text='家庭住址', null=True)),
                ('avatar', models.CharField(help_text='学生照片', max_length=250)),
                ('student', models.OneToOneField(help_text='学生表一对一关系', on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
            options={
                'verbose_name': '学生详细信息',
                'verbose_name_plural': '学生详细信息',
                'db_table': 'tb_info',
            },
        ),
    ]
